/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Secciones.Menu;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import com.Vista.secciones.facturaPanel;
import java.awt.Color;

/**
 *
 * @author Sofia Useche
 */
public class Carnes extends javax.swing.JPanel {

    private facturaPanel facturaPanel;

    /**
     * Creates new form Carnes
     */
    public Carnes() {
        initComponents();
        configurarBoton(BotonTernera, "Ternera a la llanera", "/ternera-a-la-llanera.jpeg", "$30000",null, "$40000" );
        configurarBoton(BotonCerdo, "Cerdo asado", "/cerdo-asado.jpeg", "$5000",null,"$40000");
        configurarBoton(BotonCordero, "Cordero al horno", "/cordero-al-horno-.jpeg", "$30000","Solo domingos","$40000");
        configurarBoton(BotonCarnesMixtas, "Carnes mixtas", "/carnes-mistas.jpeg", "$30000","Res/cerdo, res/cordero, cerdo/cordero","$40000");
        configurarBoton(BotonTricarne, "Tricarne", "/tricarne.jpeg", "$70000","Res, cerdo, cordero", null);

        facturaPanel = new facturaPanel();
        facturaPanel.setVisible(false);

        addActionListenerToButton(BotonTernera);
        addActionListenerToButton(BotonCerdo);
        addActionListenerToButton(BotonCordero);
    }

    private void addActionListenerToButton(JButton button) {
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                toggleFacturaPanelVisibility();
                registerPurchase();
            }
        });
    }

    private void toggleFacturaPanelVisibility() {
        facturaPanel.setVisible(!facturaPanel.isVisible());
    }

    private void registerPurchase() {
        // Add code to register the purchase in the Orden_Detalle table
    }

    private void btnPedidoActionPerformed(ActionEvent evt) {
        Cubierta1.setBackground(new Color(230, 230, 230, 240));
        PanelCubierta.setVisible(true);
        PanelCubierta.removeAll();
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
        PanelCubierta.add(Cubierta1);
        PanelCubierta.repaint();
        PanelCubierta.revalidate();
    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void configurarBoton(javax.swing.JButton boton, String texto, String urlImagen, String precio, String descripcion, String precio1) {
    // Inicia el texto HTML para el botón
    StringBuilder html = new StringBuilder();
    html.append("<html>")
        .append("    <div style=\"text-align: center; margin-top: 10px;\">")
        .append("        <font style=\"font-size:12px;\"><b>").append(texto).append("</b></font>")
        .append("    </div>");

    // Agrega descripción si está disponible
    if (descripcion != null && !descripcion.trim().isEmpty()) {
        html.append("    <div style=\"text-align: center; margin-top: 10px;\">")
            .append("        <font style=\"font-size:10px;\">").append(descripcion).append("</font>")
            .append("    </div>");
    }

    // Agrega el precio si está disponible
    if (precio != null && !precio.trim().isEmpty()) {
        html.append("    <div style=\"text-align: center; margin-top: 10px;\">")
            .append("        <font style=\"font-size:10px;\">").append(precio).append("</font>")
            .append("    </div>");
    }

    // Agrega precio1 si está disponible
    if (precio1 != null && !precio1.trim().isEmpty()) {
        html.append("    <div style=\"text-align: center; margin-top: 10px;\">")
            .append("        <font style=\"font-size:10px;\">").append(precio1).append("</font>")
            .append("    </div>");
    }

    html.append("</html>");

    // Configura el botón con la imagen y el texto generado
    boton.setIcon(icono(urlImagen, 143, 120)); 
    boton.setText(html.toString());
    boton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM); 
    boton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
}
    
    public Icon icono(String url, int ancho, int alto) {
    ImageIcon img = new ImageIcon(getClass().getResource(url));
    return new ImageIcon(img.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Buttons_Carnes = new javax.swing.JPanel();
        BotonTernera = new javax.swing.JButton();
        BotonCerdo = new javax.swing.JButton();
        BotonCordero = new javax.swing.JButton();
        BotonCarnesMixtas = new javax.swing.JButton();
        BotonTricarne = new javax.swing.JButton();
        Cubierta1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        Buttons_Carnes.setBackground(new java.awt.Color(204, 204, 204));
        Buttons_Carnes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonTernera.setBackground(new java.awt.Color(255, 255, 255));
        BotonTernera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonTernera.setForeground(new java.awt.Color(0, 0, 0));
        BotonTernera.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonTernera.setBorderPainted(false);
        BotonTernera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonTernera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTerneraActionPerformed(evt);
            }
        });
        Buttons_Carnes.add(BotonTernera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 173, 280));

        BotonCerdo.setBackground(new java.awt.Color(255, 255, 255));
        BotonCerdo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonCerdo.setForeground(new java.awt.Color(0, 0, 0));
        BotonCerdo.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonCerdo.setBorderPainted(false);
        BotonCerdo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerdoActionPerformed(evt);
            }
        });
        Buttons_Carnes.add(BotonCerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 173, 280));

        BotonCordero.setBackground(new java.awt.Color(255, 255, 255));
        BotonCordero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonCordero.setForeground(new java.awt.Color(0, 0, 0));
        BotonCordero.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonCordero.setBorderPainted(false);
        BotonCordero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCordero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCorderoActionPerformed(evt);
            }
        });
        Buttons_Carnes.add(BotonCordero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 173, 280));

        BotonCarnesMixtas.setBackground(new java.awt.Color(255, 255, 255));
        BotonCarnesMixtas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonCarnesMixtas.setForeground(new java.awt.Color(0, 0, 0));
        BotonCarnesMixtas.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonCarnesMixtas.setBorderPainted(false);
        BotonCarnesMixtas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCarnesMixtas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCarnesMixtasActionPerformed(evt);
            }
        });
        Buttons_Carnes.add(BotonCarnesMixtas, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 175, 280));

        BotonTricarne.setBackground(new java.awt.Color(255, 255, 255));
        BotonTricarne.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonTricarne.setForeground(new java.awt.Color(0, 0, 0));
        BotonTricarne.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(255, 255, 255)));
        BotonTricarne.setBorderPainted(false);
        BotonTricarne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonTricarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTricarneActionPerformed(evt);
            }
        });
        Buttons_Carnes.add(BotonTricarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 173, 280));

        jScrollPane2.setViewportView(Buttons_Carnes);

        Cubierta1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Salida.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Cantidad");

        jSpinner1.setBorder(null);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Observaciones");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 51, 51));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Cancelar");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);

        jButton11.setBackground(new java.awt.Color(58, 179, 28));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Aceptar");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(62, 62, 62)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(126, 126, 126)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        Cubierta1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 310, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Cubierta1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Cubierta1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTerneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTerneraActionPerformed
        btnPedidoActionPerformed(evt);
    }//GEN-LAST:event_BotonTerneraActionPerformed

    private void BotonCerdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerdoActionPerformed
        btnPedidoActionPerformed(evt);
    }//GEN-LAST:event_BotonCerdoActionPerformed

    private void BotonCorderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCorderoActionPerformed
        btnPedidoActionPerformed(evt);
    }//GEN-LAST:event_BotonCorderoActionPerformed

    private void BotonCarnesMixtasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCarnesMixtasActionPerformed
        btnPedidoActionPerformed(evt);
    }//GEN-LAST:event_BotonCarnesMixtasActionPerformed

    private void BotonTricarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTricarneActionPerformed
        btnPedidoActionPerformed(evt);
    }//GEN-LAST:event_BotonTricarneActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCarnesMixtas;
    private javax.swing.JButton BotonCerdo;
    private javax.swing.JButton BotonCordero;
    private javax.swing.JButton BotonTernera;
    private javax.swing.JButton BotonTricarne;
    private javax.swing.JPanel Buttons_Carnes;
    private javax.swing.JPanel Cubierta1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
